import { createSlice } from "@reduxjs/toolkit";

/**
 * Initial state of the settings slice.
 * @type {Object}
 * @property {string} currentSettingChoice - The current selected setting choice.
 */
const initialState = {
    currentSettingChoice: "Profile",  // Fixed typo here
    theme: "baselightTheme"
};

/**
 * Slice for managing the current settings-related state.
 * @type {Object}
 * @property {string} name - The name of the slice.
 * @property {Object} initialState - The initial state of the slice.
 * @property {Object} reducers - The reducers for handling actions.
 */
export const SettingSlice = createSlice({
    name: 'settings', // Name of the slice
    initialState, // Initial state of the slice
    reducers: {
        /**
         * Sets the current setting choice in the state.
         * @param {Object} state - The current state.
         * @param {Object} action - The action object containing the payload.
         * @param {string} action.payload - The new setting choice to set.
         */
        setCurrentSettingChoice: (state, action) => {
            state.currentSettingChoice = action.payload;
        },
        setTheme: (state, action) => {
            state.theme = action.payload;
        },
        /**
         * Resets the current setting choice in the state.
         * @param {Object} state - The current state.
         */
        resetCurrentSettingChoice: (state) => {
            state.currentSettingChoice = "Profile";
        }
    },
});

// Export the action creators generated by createSlice
export const { setCurrentSettingChoice, resetCurrentSettingChoice, setTheme } = SettingSlice.actions;

/**
 * The reducer function for the SettingSlice.
 * @type {function} - The reducer function to be used in the store.
 */
export default SettingSlice.reducer;
